In [12]:
import torch as t

In [13]:
print(torch.__version__)

2.5.1+cu124


In [14]:
if torch.cuda.is_available():
    print("GPU is available")
    print("GPU is ",torch.cuda.get_device_name())
else:
    print("GPU is not available")

GPU is available
GPU is  NVIDIA GeForce GTX 1650


In [17]:
# creating tensor in pytorch
t.empty(2,3) #it allocate memory for us 

tensor([[1.4239e-12, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 4.4842e-44, 0.0000e+00]])

In [18]:
# using zeros
t.zeros(3,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [19]:
# using ones
t.ones(2,2)

tensor([[1., 1.],
        [1., 1.]])

In [20]:
# using rand
t.rand(3,3)

tensor([[0.0082, 0.5671, 0.4668],
        [0.1098, 0.5120, 0.1871],
        [0.3798, 0.3834, 0.4747]])

In [23]:
# manual seed 
t.manual_seed(10)
t.rand(2,2)

tensor([[0.4581, 0.4829],
        [0.3125, 0.6150]])

In [25]:
# using tensor or making custom tensor
t.tensor([[2],[3]])

tensor([[2],
        [3]])

In [26]:
# arrange
t.arange(0,5,1)

tensor([0, 1, 2, 3, 4])

In [30]:
# using linspace it is linear space
t.linspace(1,6,2)

tensor([1., 6.])

In [31]:
# using eye or identity matrix or tensor
t.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [33]:
# using full it fill with costum values
t.full((2,2),3)

tensor([[3, 3],
        [3, 3]])

In [34]:
# tensor shapes


In [37]:
x = t.tensor([[1,2,3],[4,5,6]])

In [38]:
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [39]:
x.shape

torch.Size([2, 3])

In [40]:
 # if you wnat to make tensor with same previous tensor shape
t.empty_like(x)

tensor([[          771331272,                   0, 7090410953182806015],
        [8315178084276987250, 7009357371389667167,     419059965719404]])

In [41]:
# or we also have 
t.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [42]:
# or 
t.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [43]:
# tensor datat type
x.dtype

torch.int64

In [44]:
# we can specify data type 
y = t.tensor([[1,2,3],[2,3,4]],dtype=t.float32)

In [45]:
y

tensor([[1., 2., 3.],
        [2., 3., 4.]])

In [46]:
# also we can change it 
y.to(t.int32)

tensor([[1, 2, 3],
        [2, 3, 4]], dtype=torch.int32)