In [16]:
import numpy as np

In [17]:
# Create a 5D tensor of shape (2, 3, 4, 5, 6)
tensor_5d = np.random.rand(2, 3, 4, 5, 6)  # Random values for demonstration

In [18]:
# Print the shape of the tensor
print("Shape of the 5D Tensor:", tensor_5d)

Shape of the 5D Tensor: [[[[[6.89186131e-02 2.90786293e-01 7.60144129e-01 8.83040940e-01
     2.70565826e-01 8.84950562e-01]
    [7.34670796e-01 9.28039009e-01 3.14612999e-02 5.29334418e-01
     1.95840345e-01 5.60902803e-01]
    [4.90720365e-01 4.29327568e-01 8.45588596e-01 4.66852845e-01
     7.35674052e-02 4.18271102e-01]
    [2.40691045e-01 8.60882051e-01 6.47134061e-01 1.97513919e-01
     7.61647602e-01 3.07449377e-01]
    [6.39894927e-01 2.78742972e-01 5.53330840e-01 6.97019127e-01
     1.52920934e-01 3.87957768e-01]]

   [[5.67934633e-01 5.56106646e-01 3.22717579e-01 3.40389352e-02
     9.20915471e-01 5.96150149e-02]
    [6.30547982e-01 8.84124225e-01 4.55658601e-01 9.49781736e-01
     8.93381996e-01 7.15498081e-01]
    [4.63245943e-01 6.97766217e-01 6.73316280e-01 7.47784266e-01
     1.71424224e-01 8.38750072e-01]
    [5.19490215e-01 9.61389816e-01 7.24489443e-01 4.65668737e-01
     3.12361260e-01 5.85197681e-01]
    [6.67559427e-01 1.02616246e-01 6.27572062e-01 4.30280434e-01


In [6]:
# Access specific elements or slices
# Example: Access the element at position (1, 2, 3, 4, 5)
element = tensor_5d[1, 2, 3, 4, 5]
print("Element at (1, 2, 3, 4, 5):", element)

Element at (1, 2, 3, 4, 5): 0.2528129685698721


In [11]:
# Slice: Extract a 4D slice by fixing the first index
slice_4d = tensor_5d[1, :, :, :, :]
print("Shape of the 4D slice:", slice_4d)

Shape of the 4D slice: [[[[0.41083882 0.18180731 0.70223235 0.47318766 0.50435653 0.60376195]
   [0.54793304 0.33438982 0.45815284 0.90183261 0.97749421 0.77284814]
   [0.83271627 0.47304401 0.90616953 0.74199994 0.18855598 0.93700077]
   [0.43489251 0.921816   0.39598896 0.95688563 0.5195681  0.97314615]
   [0.12280079 0.43462385 0.60498495 0.26562589 0.47661888 0.68118472]]

  [[0.88814086 0.8511991  0.46043571 0.48638178 0.65318702 0.96381457]
   [0.29531554 0.03937296 0.64141669 0.73091276 0.46516208 0.37943552]
   [0.79442182 0.69489615 0.30956044 0.92987529 0.88663783 0.12426143]
   [0.2466512  0.90449031 0.04600486 0.99334145 0.74386859 0.59671017]
   [0.66818929 0.12145689 0.26311603 0.5934981  0.33283418 0.09621784]]

  [[0.95948488 0.47825607 0.04469766 0.81290037 0.65190327 0.32029614]
   [0.45766062 0.0181265  0.18669421 0.56780489 0.30169804 0.47231898]
   [0.49909986 0.21085491 0.51003929 0.69820616 0.52265599 0.88493472]
   [0.86166257 0.04235978 0.59921702 0.1531066  0.

In [14]:
import numpy as np

# Create a small 5D tensor with shape (2, 2, 2, 2, 2) for visualization
tensor_5d = np.arange(2*2*2*2).reshape(2, 2, 2, 2)

# Print the entire tensor for visualization
print("5D Tensor:")
print(tensor_5d)

# Access a specific element, e.g., at position (1, 1, 1, 1, 1)
specific_element = tensor_5d[1, 1, 1, 1]
print("\nElement at (1, 1, 1, 1, 1):", specific_element)

# Slice the tensor, e.g., fix the first index and print the remaining 4D slice
# slice_4d = tensor_5d[1, :, :, :, :]
# print("\n4D Slice with the first dimension fixed to 1:")
# print(slice_4d)


5D Tensor:
[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]]

Element at (1, 1, 1, 1, 1): 15
